// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://mxcwkcpfiuqdndmecljr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Y3drY3BmaXVxZG5kbWVjbGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQwMjEwMTgsImV4cCI6MjA4OTU5NzAxOH0.2srx_o05JY0z3UBJw6--hfdCOGmzc8Xd6gqXp6rhqNM";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);